# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = with config.boot.kernelPackages; [
      v4l2loopback
    ];
    kernelParams = [
      "i915.enable_psr=0"
      "i915.enable_fbc=1"
    ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/1f416b78-cafd-4ad1-a37c-13142bfff2fd";
      fsType = "btrfs";
      options = [
        "subvol=@"
        "compress=zstd"
        "autodefrag"
        "space_cache=v2"
      ];
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/4259-FED9";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    "/important" = {
      device = "/dev/disk/by-uuid/1f416b78-cafd-4ad1-a37c-13142bfff2fd";
      fsType = "btrfs";
      options = [
        "subvol=@important"
        "compress=zstd"
        "autodefrag"
        "space_cache=v2"
      ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/afe724bc-f57a-4930-b58a-487093804f15";
      fsType = "btrfs";
      options = [
        "subvol=@home"
        "compress=zstd"
        "autodefrag"
        "space_cache=v2"
      ];
    };

    "/opt/games" = {
      device = "/dev/disk/by-uuid/afe724bc-f57a-4930-b58a-487093804f15";
      fsType = "btrfs";
      options = [
        "subvol=@games"
        "compress=zstd"
        "autodefrag"
        "space_cache=v2"
      ];
    };

    "/srv/backups" = {
      device = "/dev/disk/by-uuid/afe724bc-f57a-4930-b58a-487093804f15";
      fsType = "btrfs";
      options = [
        "subvol=@backups"
        "compress=zstd"
        "autodefrag"
        "space_cache=v2"
      ];
    };

    "/srv/vms" = {
      device = "/dev/disk/by-uuid/afe724bc-f57a-4930-b58a-487093804f15";
      fsType = "btrfs";
      options = [
        "subvol=@vms"
        "compress=zstd"
        "autodefrag"
        "space_cache=v2"
      ];
    };
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/e6368fbe-43b1-4f57-8bfc-e0fda7849036"; }
  ];

  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 35;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
